### ISSUE TITLE
"Duck Sightings" Folder

### ISSUE THREAD

**Issue by JohnVidler** [perayson/pond#1]
Just for fun - a folder with a gallery of duck sightings around campus.

Plus, it would show off how the ducks look on various materials :)

**Comment by perayson** [comment]
Agreed! Although for a moment there, I thought you meant real ducks :-) They've already reached Sheffield yesterday!

**Comment by JohnVidler** [comment]
Awesome! I'll start up the sightings folder in a bit then :)
